### ISSUE TITLE
Armor Class missing parenthesis noting armor, shield or natural armor

### ISSUE THREAD

**Issue by Wyrmwood** [5e-bits/5e-database#345] opened 2021-02-13 18:37 UTC
For example, 
https://www.dnd5eapi.co/api/monsters/goblin
```
{
...
  "armor_class": 15,
```
is just a number. Instead it should be an object with
```
"armor_class":  {
    "value": 15,
    "desc": "15 (leather armor, shield)"

}
```
Or something similar. This information is required to appropriately choose versatile damage.

**Comment by bagelbits** [comment] 2021-02-15 19:57
I'm going to close this in favor of #280 as it's a duplicate of it. There is also an open pull request to try and address it but I think it's on hold for right now.

**Closed as completed by bagelbits** 2021-02-15 19:57 UTC
