### ISSUE TITLE
Use Markdown to represent rich text

### ISSUE THREAD

**Issue by fergcb** [5e-bits/5e-database#337] opened 2021-01-06 16:51 UTC
# The Problem
Currently, there are some oddities with the way the API represents rich text fields, such as spell descriptions. The present strategy is to separate paragraphs into their own strings, as items in an array. This is practical for rendering - `for each` over the array, and produce a `<p>` tag for each string (or your stack's equivalent); however, this approach is severely limiting when it comes to complex mark-up, such as tables, subheadings, etc.

Compliance with this approach leads to some interesting formatting in the API's data. For example, the spell `scrying` has two tables, in the source:

![image](https://user-images.githubusercontent.com/6972523/103794027-21c8ce00-503c-11eb-93cf-097cdd5f4dfc.png)

Whereas the format given in the API is distant from the source, and carries no information about emphasis, where tables begin and end, and treats table rows as distinct paragraphs:

```json
{
  "index": "scrying",
  "name": "Scrying",
  "desc": [
    "You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you're casting this spell, it can fail the saving throw voluntarily if it wants to be observed.",
    "Knowledge & Save Modifier",
    "Secondhand (you have heard of the target) +5",
    "Firsthand (you have met the target) +0",
    "Familiar (you know the target well) -5",
    "Connection & Save Modifier",
    "Likeness or picture -2",
    "Possession or garment -4",
    "Body part, lock of hair, bit of nail, or the like -10",
    "On a successful save, the target isn't affected, and you can't use this spell against it again for 24 hours.",
    "On a failed save, the spell creates an invisible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration. A creature that can see invisible objects sees the sensor as a luminous orb about the size of your fist.",
    "Instead of targeting a creature, you can choose a location you have seen before as the target of this spell. When you do, the sensor appears at that location and doesn't move."
  ],
  "...": "..."
}
```

# Proposed Solution: Markdown
If we replace arrays of strings with single strings that follow a markdown standard, we'll be able to represent entities like tables with far greater ease. We would have to choose a single markdown flavour, for consistency. GitHub Flavoured Markdown (GFM) is a solid choice; it is used widely, we already write our PRs and Issues with it, it is compatible with the majority of markdown parsers across various languages, and encompasses most (if not all) of the mark-up required to faithfully replicate the formatting in the SRD.

### Pros:
- We can use tables, headings, etc.
- Markdown is an industry standard & well supported, so data-receivers should be able to process the data easily, and contributors to the repo will likely already have some level of comfort with the syntax.
- Markdown maintains some level of human-readability, even if unrendered.

### Cons
- The source may be less readable, as raw newlines aren't acceptable in JSON strings. This is fairly minor, as markdown can be edited externally, if necessary, and copied in to a JSON string.

**Comment by scarabdesign** [comment] 2021-01-06 22:28
I suppose using markdown would be fine for stuff like headers, but as far as tabular data, it may complicate matters. 
Firstly, it assumes the all consumers will be needing the markdown (instead of just needing the raw unformatted data) and in those cases where they don't, a developer would need to try to strip them out. Perhaps if there was a way to optionally include it with the response, I'd be more in favor of it.
Second, this won't address the problem with the way these tables are stored now, in that it mixes the row data into a single line as if for display, so a developer will still need to figure out where to split the line to separate the columns if they want to be able to adjust the final display of the result.
As an alternative option, I'd propose more of a structural solution for tables. Include an object with an attribute of "table":
```
{
  "index": "scrying",
  "name": "Scrying",
  "desc": [
    "You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you're casting this spell, it can fail the saving throw voluntarily if it wants to be observed.",
    {
        "table": "Knowledge Save Modifiers",
        "columns": ["knowledge", "save modifier"],
        "rows": [
            ["Secondhand (you have heard of the target)", "+5"],
            ...
        ]
    },
    {
        "table": "Connection Save Modifiers",
        "columns": ["connection", "save modifier"],
        "rows": [
            ["Likeness or picture", "-2"],
            ...
        ]
    },
    "On a successful save, the target isn't affected, and you can't use this spell against it again for 24 hours.",
    ...
}
```
This sort of approach would take possible guess-work out of what markdown should do what and it also separates the value of the entries ("-2") vs the label ("Likeness or picture"). You won't lose the order.

**Comment by scarabdesign** [comment] 2021-01-06 22:46
I also realize that my proposed solution is more wordy, which may or may not be good. Here's another solution that would be as effective:

```
{
  "index": "scrying",
  "name": "Scrying",
  "desc": [
    "You can see and hear a ...",
    [
       ["knowledge", "save modifier"],
       ["Secondhand (you have heard of the target)", "+5"],
       ...
    ],
    [
        ["connection", "save modifier"],
        ["Likeness or picture", "-2"],
        ...
    ],
    "On a successful save...",
    ...
}
```

**Comment by fergcb** [comment] 2021-01-06 22:50
I kind of think that implementing our own way of describing tables is a step in the *wrong* direction, if anything. The point of `desc` attributes is to provide human-facing data, not to be digestible by data-consuming apps for, say, calculations or whatever.

If we want to provide tables in a computer-friendly format, rather than a human-facing one, that should be in its own, separate field in the document.

**Comment by fergcb** [comment] 2021-01-06 22:52
As for optionally including fields in a response, we've got GraphQL support now (though in an early stage), so if people need to reduce response sizes, that's how they'd achieve that.

**Comment by fergcb** [comment] 2021-01-06 22:57
Oh, sorry for the triple post, but I don't want to ninja-edit, for this to be missed. For the "the developer needs to figure out where to split the line" issue, we can specify newlines with "\n", in JSON strings. This is obviously a necessity of transitioning to Markdown, in which newlines are part of the syntax. A double newline indicates a paragraph break in Markdown. In terms of "what markdown should do what", markdown syntax is largely unambiguous by its nature, and standard implementations of markdown parsers (which are available across pretty much every platform/language), behave in predictable ways. This is one of the advantages of the transition from our current syntax (or in place of implementing a proprietary table syntax), which would require data-consumers to design their own methods of interpretation.

**Comment by scarabdesign** [comment] 2021-01-07 00:19
>The point of desc attributes is to provide human-facing data, not to be digestible by data-consuming apps for, say, calculations or whatever.

However, there are tabular data there, and as such should be treated like tabular data, in my opinion. You are taking away possibilities of something more that can be done with that data, or at least making it harder to use outside of display.

The issue is that we are making assumptions about how a developer wants to display the data. Including markdown that turns the data into tables assumes the developer wants the table, not just the data. For instance, someone using the api to make a data driven application may want those data in a drop down instead (generally, not specifically for the example provided), now they are left with trying to strip out the markdown. 

Or in another instance, say I want to tie a die roll to one of those tables. Teleport spell: "The GM rolls d100 and consults the table". I can make a simple program that takes the die roll and gives back a result based on that table without needing to visually consult the table. It's these sort of things that make an api like this so powerful.

> If we want to provide tables in a computer-friendly format, rather than a human-facing one, that should be in its own, separate field in the document.

I'd say this is a special case, since it's tabular data but it's order in the "desc" field is important. Moving it out of desc breaks it apart from it's descriptive strings before and after the table. Perhaps then it would requiring some sort of flag to point to "see figure A" in that position. Probably not ideal.

As far as using a newline between the label and value, wouldn't this put the second column, "-2" in this instance, on the next line down and break the table?

Anyway, my 2 bits are just that, and I'll still continue to use the api, no matter what the decision here :)

**Comment by fergcb** [comment] 2021-01-07 01:08
> Including markdown that turns the data into tables assumes the developer wants the table, not just the data.

I think you're entirely missing the point of this issue, maybe?

As I said `desc` attributes currently are intended to be human-facing data, directly ported from the SRD. This issue seeks to improve the way these fields to their job. It **does not** seek to change the purpose of the fields (i.e. to make them better for computer digestion).

As I have said, if we want to include tabular data for computer digestion, it should be in its own attribute.

> As far as using a newline between the label and value, wouldn't this put the second column, "-2" in this instance, on the next line down and break the table?

I'm not sure what you're talking about, here. I haven't suggested anything like this. Again, I think you're misunderstanding the substance of this issue.

## This Issue is ONLY concerned with improving the formatting of data intended for HUMAN READABILITY

If you wish to open a separate issue concerned with providing unique, tabular data in certain types of documents, because it would improve your experience using the API, please feel free to do so.

**Comment by bagelbits** [comment] 2021-01-07 10:15
@fergcb I don't think I could have put it better. And thanks for opening this issue for me.

**Comment by bagelbits** [comment] 2021-01-07 10:24
@scarabdesign To put this another way, this issue is only dealing with standardizing how we format our human readable text that is pulled directly out of the SRD. Anything more than that, i.e. extracting additional data out, is out of scope for this issue. If you have some ideas, feel free to open another issue to create that discussion. I'd love to hear it.

**Comment by bagelbits** [comment] 2021-01-07 10:32
@fergcb Back to the matter at hand, I remember we had some debate on whether to make use of `\n` in one long string or an array of strings. I assume you're still in favor of the former?

**Comment by fergcb** [comment] 2021-01-07 10:36
I'm definitely in favour of putting the newlines in the data, yeah.

This would make the data slightly less readable to us editing it, or to anyone trying to view the raw JSON, I suppose. But to me that's an acceptable tradeoff over making the consumer take the extra step in processing the data themselves.

**Comment by bagelbits** [comment] 2021-01-07 11:01
On the other hand, it's not much of an extra step and it makes our lives considerable easier. (And also makes the PRs easier to see what has changed on a line).

**Comment by bagelbits** [comment] 2021-01-07 11:02
But honestly, I don't feel that strongly about it. I just want to have fair consideration for both approaches.

**Comment by ogregoire** [comment] 2021-01-07 12:02
My take is "don't reinvent the wheel".

Markdown is popular and well known and works well in a variety of different contexts.

`desc` is just a text field. There's no reason to have it split on lines. If anything, it's just a faulty design to do so. So there should be if not linebreaks at least `\n` in it.

If we want to reflect the metadata that is the structure of the description, the text field should contain some markup language. Given the popularity of markdown as well as the readability of it, I strongly suggest using it.

Any attempt to make our own markup language is flawed. @scarabdesign's [idea](https://github.com/bagelbits/5e-database/issues/337#issuecomment-755763014) introduces a new level of complexity both for the user and the writer, and overall makes everything less readable.

**Comment by ogregoire** [comment] 2021-01-07 12:11
> The issue is that we are making assumptions about how a developer wants to display the data. Including markdown that turns the data into tables assumes the developer wants the table, not just the data. For instance, someone using the api to make a data driven application may want those data in a drop down instead (generally, not specifically for the example provided), now they are left with trying to strip out the markdown.

We are definitely *trying* to make all the data themselves in structured data, but we can't yet. But the text is part of the SRD, and we write it down as part of the `desc` field. So we basically have two things here: the textual representation and the extracted data.

We should definitely keep the textual representation as is, and if we want, we improve its representation. As @fergcb said, we are not speaking about the data itself, we are speaking about the textual representation. So this issue is spot-on and suggest the most appropriate fix. Writing the data in markdown form doesn't invalidate the data we've extracted so far.

To be clear, we should have both the data and a textual representation. We come from the text and are migrating towards the data, piece by piece. Transforming the text into markdown doesn't invalidate the fact that at some point in the future, we want to have a data form of the text.

**Comment by bagelbits** [comment] 2021-01-07 19:58
Cool, I'm fine with just using /n then. I think we're good to start developing this if someone wants to pick up the torch.

**Comment by reessm01** [comment] 2021-01-08 04:24
I hope folks don't mind me weighing in. I mentioned it yesterday that might have sparked the conversation. Without ruling out how I am rendering the data, from my perspective there currently isn't anything to tap into that indicates that certain entries were table formatted. This is what ends up happening (if one is just simply iterating thru the content):
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/14968605/103974081-1ca07780-513f-11eb-9a91-3443fe183d34.png">
What tipped me off that it was a table was the sentence before the entries.

**Comment by bagelbits** [comment] 2021-01-08 04:26
Out of curiosity, is that a spell or magic item?

**Comment by reessm01** [comment] 2021-01-08 04:27
> Out of curiosity, is that a spell or magic item?

Spell, specifically reincarnate.

**Comment by bagelbits** [comment] 2021-01-08 10:29
Yeah that makes sense. I think magic items and rules are the only things that use Markdown. Spells are something that would need it still. Which would make it easier to render tables.

**Comment by MikkelPaulson** [comment] 2022-01-12 18:26
The examples cited in this issue have all been reformatted as Markdown tables as of #437. I'm sure there's material elsewhere that still needs to be converted; not sure if this issue should remain open until that's confirmed done or not.

**Comment by bagelbits** [comment] 2022-01-12 21:18
I think you're right!

**Closed as completed by bagelbits** 2022-01-12 21:18 UTC
